# Generated by Django 4.1.1 on 2022-09-27 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=250, verbose_name='Должность')),
                ('employment_date', models.DateField(verbose_name='Дата приема на работу')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Зарплата')),
                ('salary_currency', models.CharField(choices=[('RUB', 'рублей'), ('USD', 'доллары'), ('EUR', 'евро')], max_length=3, verbose_name='валюта зарплаты')),
            ],
        ),
        migrations.CreateModel(
            name='Superior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef', to='employee.employee', verbose_name='Начальник')),
                ('subordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinate', to='employee.employee', verbose_name='Подчиненный')),
            ],
            options={
                'unique_together': {('chef', 'subordinate')},
            },
        ),
    ]
