# Generated by Django 4.1.1 on 2022-09-27 18:12

from django.db import migrations, models
import django.db.models.deletion
import employee.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='superior',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employee',
            name='role_level',
            field=models.IntegerField(choices=[('Executive', 1), ('Head of dep', 2), ('Chief', 3), ('Second chief', 4), ('rookie', 5)], default=1, verbose_name='уровень в компании'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary_currency',
            field=models.CharField(choices=[('RUB', 'рубли'), ('USD', 'доллары'), ('EUR', 'евро')], max_length=3, verbose_name='валюта зарплаты'),
        ),
        migrations.AlterField(
            model_name='superior',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef', to='employee.employee', validators=[employee.validators.validate_roles], verbose_name='Начальник'),
        ),
    ]
