# Generated by Django 4.1.1 on 2022-09-27 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_superior_unique_together_employee_role_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superior',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chef', to='employee.employee', verbose_name='Начальник'),
        ),
    ]
